export const DEPARTMENTS = [
  { slug: "cse", name: "Computer Science & Engineering" },
  { slug: "eee", name: "Electrical and Electronics Engineering" },
  { slug: "math", name: "Mathematics" },
  { slug: "sta", name: "Statistics" },
  { slug: "acce", name: "Applied Chemistry and Chemical Engineering" },
  { slug: "accounting", name: "Accounting" },
  { slug: "agriculture", name: "Agriculture" },
  { slug: "agroprocess", name: "Food and Agroprocess Engineering" },
  { slug: "architecture", name: "Architecture" },
  { slug: "biochemistry", name: "Biochemistry and Molecular Biology" },
  { slug: "botany", name: "Botany" },
  { slug: "chemistry", name: "Chemistry" },
  { slug: "civil", name: "Civil Engineering" },
  { slug: "economics", name: "Economics" },
  { slug: "english", name: "English" },
  { slug: "environmental", name: "Environmental Science & Disaster Management" },
  { slug: "finance", name: "Finance and Banking" },
  { slug: "fisheries", name: "Fisheries and Marine Bioscience" },
  { slug: "genetic", name: "Biotechnology and Genetic Engineering" },
  { slug: "history", name: "History" },
  { slug: "ir", name: "International Relations" },
  { slug: "law", name: "Law" },
  { slug: "management", name: "Management Studies" },
  { slug: "marketing", name: "Marketing" },
  { slug: "pharmacy", name: "Pharmacy" },
  { slug: "physics", name: "Physics" },
  { slug: "political", name: "Political Science" },
  { slug: "psychology", name: "Psychology" },
  { slug: "sociology", name: "Sociology" },
  { slug: "tourism", name: "Tourism and Hospitality Management" },
  { slug: "veterinary", name: "Animal Science and Veterinary Medicine" },
  { slug: "islamic", name: "Islamic" },
  { slug: "nonacademic", name: "Non Academic" }
];
